### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by dlpnet** [nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode#26]
I am using gitPod and cannot find this extension. It looks like it needs to be published on Open VSX:
https://www.gitpod.io/blog/open-vsx-in-gitpod

**Comment by nagata-yoshiteru** [comment]
Thank you for your comment.
I published this extention to Open VSX.

**Comment by dlpnet** [comment]
🎉  it works ! thank you
