### ISSUE TITLE
Auto refresh isn't working

### ISSUE THREAD

**Issue by mythmon** [nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode#33]
Opening a PPM file works fine, but it isn't reloading when that image changes. I am writing to the file whenever my source file changes, and the image display never updates. I'm running on Windows. Closing the file and opening it again displays the new contents.

**Comment by BenWeisz** [comment]
I can take a look

**Comment by mythmon** [comment]
Thanks for taking a look. The image I was modifying was in the root directory of my workspace (if I had a .git directory, it would have been a sibling to that). Does it need to  be in a subdirectory? Does not having Git make a difference?

**Comment by BenWeisz** [comment]
Nope, so ideally it would work form anywhere. I've push some changes on a branch and we'll try to merge everything in in the next few days. What are the approximate dimensions of the file? If its large, could you please attach as a comment below, thanks!

**Comment by mythmon** [comment]
If it matters, I'm writing to this file via command line redirection in Powershell.

```
$ cargo run > image.ppm
```

I've tested with images as big as 1920x1080 and as small as 16x9. Here is an example of the 16x9 `.ppm` file.

```ppm
P3
16 9
255
255 176 146
255 173 141
255 171 137
255 167 131
255 164 126
255 161 122
255 160 120
255 159 118
255 160 119
255 162 122
255 164 127
255 167 132
255 170 137
255 173 141
255 176 145
255 178 149
255 181 154
255 179 151
255 176 146
255 174 142
255 171 137
255 168 133
255 166 130
255 166 129
255 166 130
255 168 133
255 171 137
255 174 142
255 176 146
255 179 150
255 182 154
255 184 157
255 188 164
255 187 162
255 184 158
255 181 154
255 179 151
255 176 146
249 169 139
237 160 130
246 167 137
255 177 146
255 179 150
255 182 154
255 184 158
255 186 161
255 188 164
255 190 166
255 195 175
255 194 172
255 193 171
255 191 168
255 189 166
230 166 142
173 121 102
171 117 96
174 121 101
231 167 144
255 189 165
255 191 168
255 192 170
255 194 172
255 195 174
255 196 175
255 202 184
255 202 184
255 201 183
255 201 182
255 200 181
184 133 115
160 111 92
160 114 97
166 117 99
178 126 107
255 200 181
255 201 182
255 202 183
255 202 184
255 202 184
255 203 185
239 190 173
230 179 162
229 178 160
217 164 145
215 161 142
162 114 96
152 107 90
150 106 89
157 110 92
165 119 102
218 166 147
224 172 154
231 181 164
233 182 165
240 192 175
246 197 181
180 115 89
179 114 87
178 114 88
177 112 85
173 111 85
154 102 81
142 100 84
146 102 86
137 95 79
157 104 82
176 114 88
178 115 89
179 116 90
181 117 91
181 116 89
180 116 90
179 115 89
178 113 86
176 113 88
170 109 84
160 106 84
143 97 80
117 81 67
109 74 60
133 91 75
154 102 81
164 108 85
170 111 86
174 112 87
177 114 87
179 117 92
178 113 86
175 113 87
175 112 86
165 107 83
163 107 85
164 106 82
161 106 84
154 103 83
150 101 82
142 94 76
149 97 76
164 107 83
168 110 87
170 109 85
175 110 83
175 111 84
178 114 88
```

**Comment by BenWeisz** [comment]
Thanks @mythmon! When the changes are ready, Ill give it a final check with this file

**Comment by BenWeisz** [comment]
Hey @mythmon , we've published the changes, please update the extension and let us know if it worked in your scenario. Thanks!

**Comment by BenWeisz** [comment]
@mythmon Have you had the chance to try out the new features? You might need to update the extension.
We are hoping to close this issue if it's working ok for you.

**Comment by mythmon** [comment]
Sorry for the slow response! This is working great now, thanks for the quick fix.

**Comment by BenWeisz** [comment]
No worries, glad we could fix it :)
