### ISSUE TITLE
P3 images not rendered

### ISSUE THREAD

**Issue by prakharpratapmall** [nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode#40]
Using v1.1.4 of the extension

I was following the [Ray tracing in one weekend](https://raytracing.github.io/books/RayTracingInOneWeekend.html) tutorial but the images generated using the sample code provided there are not rendered. 
![image](https://github.com/nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode/assets/79718151/22a25bde-25fe-4619-b144-cb5759769250)
I get this blank screen on opening the ppm file.
The contents of the ppm file are as per requirement of P3. 
Here is the code being used to generate the P3 file.
```
#include <iostream>
#include<random>
#include<ctime>
#include "vector.h"
int main() {
    srand(time(NULL));
    int nx = 300;
    int ny = 200;
    std::cout << "P3\n" << nx << " " << ny << "\n255\n";
    for (int j = ny-1; j >= 0; j--) {
        std::cerr<<"Scanlines remaining :"<<j<<std::flush;
        for (int i = 0; i < nx; i++) {
            float tmp = rand() / static_cast<float>(RAND_MAX);
            vec3 col = vec3(tmp,tmp,tmp);
            int ir = int(255.99*col[0]);
            int ig = int(255.99*col[1]);
            int ib = int(255.99*col[2]);
            std::cout << ir << " " << ig << " " << ib << " ";
        }
        std::cout<<"\n";
    }
}
```

You can view the specific `image.ppm` file [here](https://drive.google.com/file/d/1IDewXJrPT-11-Nk3zQRTNoow1L3H6kbi/view?usp=sharing) and reproduce the issue.

**Comment by BenWeisz** [comment]
Hey @prakharpratapmall please email me a copy of the problematic P3 file as well and I will take a look at it when I have a bit more time. Thanks! 

benwdev@proton.me

**Comment by BenWeisz** [comment]
@prakharpratapmall Apologies I'll take a look at the file you linked

**Comment by BenWeisz** [comment]
@prakharpratapmall Your file has null bytes between each character. Please make sure that the file contains the right bytes using a hex viewer tool such as https://hexed.it

Please take a look at our sample file for p3 in /images

Instead of redirecting std::cout to a file in the terminal I would recommend using something like fstream

**Comment by prakharpratapmall** [comment]
Oh no I just checked my uploaded file. While it does have null bytes in between it is not the original ppm file which I am having issue with. Apparently uploading it to drive changes something in the file. I am not sure how to send you the original file. It looks something like this. 
![image](https://github.com/nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode/assets/79718151/18499a5e-3145-4914-b763-594c31e88a25)
which should be fine? The only difference between the sample images you have provided and my file is the line endings. I tried changing that too but it did not help.
I will mail you the file in hopes that you receive it unchanged. 
I am also attaching it here by renaming it to `image.txt` since github doesnt allow '.ppm' files

[image.txt](https://github.com/nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode/files/11754080/image.txt)

I will also try to zip and then upload it so that the file is not changed. Check that [here](https://drive.google.com/file/d/1p6lleXDhbCkIdEwFyL_WEU9ceFqChszR/view?usp=sharing)

**Comment by prakharpratapmall** [comment]
Ah ohkay got it! thanks for the quick response. For future people facing problems specifically while redirecting std::cout can refer to [this](https://github.com/RayTracing/raytracing.github.io/discussions/1114). This worked out for me without having to switch to fstream.
